apiVersion: v1  # A versão da API do Kubernetes para recursos básicos como Secrets
kind: Secret  # O tipo de recurso, nesse caso, um Secret, que é usado para armazenar dados sensíveis, como tokens ou credenciais
metadata:
  name: zabbix-monitor-token  # O nome do Secret, que será utilizado para referenciar este recurso no cluster
  annotations:
    kubernetes.io/service-account.name: "zabbix-monitor"  # Anotação que associa o Secret a um ServiceAccount específico (neste caso, o "zabbix-monitor")
type: kubernetes.io/service-account-token  # O tipo do Secret, que indica que ele será usado como um token de serviço (ServiceAccount)
